apiVersion: v1
kind: PersistentVolume
metadata:
  name: mwdb-postgres
  labels:
    app: postgres
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mwdb-postgres
    server: 192.168.29.231
    readOnly: false

