apiVersion: v1
kind: PersistentVolume
metadata:
  name: mwdb-uploads
  labels:
    app: mwdb
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mwdb-uploads
    server: 192.168.29.231
    readOnly: false

