apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: non-prod
  # labels:
  #   app: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
  # selector:
  #   app: redis
