kind: Endpoints
apiVersion: v1
metadata:
  #name: backend-postgres
  name: redis
  namespace: non-prod
subsets:
  - addresses:
        - ip: 192.168.29.200
    ports:
      - port: 6379
        #name: backend-postgres
        #name: postgres