#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: mquery-prod
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: shurabh/mquery_redis:latest
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: redis-pv-volume-prod
      dnsPolicy: ClusterFirst
#      nodeSelector:
#        kubernetes.io/hostname: mquery-supernode.cert.pl
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: redis-pv-volume-prod
        emptyDir: {}
#        persistentVolumeClaim:
#          claimName: redis-pv-claim-prod

#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: redis
#  name: redis
#  namespace: mquery-prod
#spec:
#  externalTrafficPolicy: Cluster
#  ports:
#  - nodePort: 30165
#    port: 6379
#    protocol: TCP
#    targetPort: 6379
#  selector:
#    app: redis
#  sessionAffinity: None
#  type: NodePort  
