apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: mquery-prod
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30165
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: NodePort
