apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: samples-pv
  name: samples-pvc
  namespace: mquery-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
#  selector:
#    matchLabels:
#      app: mquery-daemon
