apiVersion: v1
kind: Service
metadata:
  name: ursadb
  namespace: mquery-prod
  labels:
    app: ursadb
spec:
  clusterIP: None
  ports:
  - port: 9281
    targetPort: 9281
  selector:
    app: ursadb

